# This file was generated by GoReleaser. DO NOT EDIT.
class Docui < Formula
  desc "TUI Client for Docker"
  homepage "https://github.com/skanehira/docui"
  url "https://github.com/gotchane/docui/releases/download/1.0.7/docui_1.0.7_Darwin_x86_64.tar.gz"
  version "1.0.7"
  sha256 "78f2ddae96ed3c272b8d17409eb054c372c86b9d8c992cc787f8e3ed3cbbd28b"
  
  depends_on "go"

  def install
    bin.install "docui"
  end

  test do
    system "#{bin}/docui", "version"
  end
end
