# This file was generated by GoReleaser. DO NOT EDIT.
class Docui < Formula
  desc "TUI Client for Docker"
  homepage "https://github.com/skanehira/docui"
  url "https://github.com/gotchane/docui/releases/download/1.0.3/docui_1.0.3_Darwin_x86_64.tar.gz"
  version "1.0.3"
  sha256 "d179ac5cd641d9545fda90226421a994db468414f5a8ec4f74ab21ef4f930d36"
  
  depends_on "go"

  def install
    bin.install "docui"
  end

  test do
    system "#{bin}/docui"
  end
end
